### ISSUE TITLE
Cant get presence-detection to work am I using all components?

### ISSUE THREAD

**Issue by AcidSleeper** [oakbrad/brad-homeassistant-config#65]
Hello.
I found your presence-detection and put it in my configuration. But Im getting error on pythonscript.
Im using Hassio on a RPi3. The indentation is correct.
My Code:

automations.yaml
```
#
# Update Meta Device Tracker
#
  - alias: "Update Niclas's Meta Tracker Home"
    trigger:
      - platform: state
        entity_id: device_tracker.Niclas_iphone, device_tracker.Niclas_owntracks, device_tracker.Niclas_nmap
        to: 'home'
      - platform: homeassistant
        event: start
    action:
      service: python_script.meta_device_tracker
      data_template:
        entity_id: '{{trigger.entity_id}}'
        meta_entity: 'Niclas'

# Add a delay here
  - alias: "Update Niclas's Meta Track Away"
    trigger:
      - platform: state
        entity_id: device_tracker.Niclas_iphone, device_tracker.Niclas_owntracks
        to: 'not_home'
        for:
          minutes: 10
    action:
      service: python_script.meta_device_tracker
      data_template:
        entity_id: '{{trigger.entity_id}}'
        meta_entity: 'Niclas'
```

and I imported the code from file "meta_device_tracker.py" in directory "python_scripts"

```
# meta_device_tracker.py
#
# https://github.com/oakbrad/brad-homeassistant-config/blob/master/python_scripts/meta_device_tracker.py
# Combine multiple device trackers into one entity
#
# Logic:  Only GPS is reliable for 'not_home'
#         Block others from marking 'not_home' but keep for 'home'
#
   
# Get Data from Automation Trigger
triggeredEntity = data.get('entity_id')
metatrackerName = "device_tracker." + data.get('meta_entity')

# Get current & new state
newState = hass.states.get(triggeredEntity)
currentState = hass.states.get(metatrackerName)
#################### ROW 18 below - Get New data #####################3
newSource = newState.attributes.get('source_type')

# If GPS source, set new coordinates
if newSource == 'gps':
  newLatitude = newState.attributes.get('latitude')
  newLongitude = newState.attributes.get('longitude')
  newgpsAccuracy = newState.attributes.get('gps_accuracy')
# If not, keep last known coordinates
else:
  if newSource is not None:
    newLatitude = currentState.attributes.get('latitude')
    newLongitude = currentState.attributes.get('longitude')
    newgpsAccuracy = currentState.attributes.get('gps_accuracy')

# Get Battery
if newState.attributes.get('battery') is not None:
  newBattery = newState.attributes.get('battery')
elif currentState.attributes.get('battery') is not None:
  newBattery = currentState.attributes.get('battery')
else:
  newBattery = None

# Set new state and icon
# Everything updates 'home'
if newState.state == 'home':
  newStatus = 'home'
  newIcon = 'mdi:home-map-marker'
# only GPS platforms update 'not_home'
elif newState.state == 'not_home' and newSource == 'gps':
    newStatus = 'not_home'
    newIcon = 'mdi:home'
# Otherwise keep old status
else: 
    newStatus = currentState.state

# Create device_tracker.meta entity
hass.states.set(metatrackerName, newStatus, {
    'icon': newIcon,
    'name': metatrackerName,
    'source_type': newSource,
    'battery': newBattery,
    'gps_accuracy': newgpsAccuracy,
    'latitude': newLatitude,
    'longitude': newLongitude,
    'last_update_source': newState.name 
})
```
Whats missing? 

Getting error on: 
2018-10-30 11:33:41 ERROR (SyncWorker_11) [homeassistant.components.python_script.meta_device_tracker.py] Error executing script: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/python_script.py", line 166, in execute
    exec(compiled.code, restricted_globals, local)
  File "meta_device_tracker.py", line 18, in <module>
TypeError: 'NoneType' object is not callable

**Another issue:** Whats the code for only showing the latest update for cellphones in groups.yaml

```
  niclasenheter:
    name: Niclas
    entities:
      - device_tracker.niclas
      - device_tracker.niclas_iphone
      - device_tracker.niclas_nmap
      - device_tracker.niclas_owntracks
      - sensor.niclas_iphone_battery_level
      - sensor.niclas_iphone_battery_state
   
# Phonegroup
  Telefoner:
    name: Telefoner
    view: yes
    entities:
      - group.niclasenheter
      
  tracked_users:
    view: no
    name: Tracked Users
    entities:
      - device_tracker.niclas
```
Thanks for all the help I can get! =)

/Niclas
